# LU-разложение

## Постановка задачи

Пусть дана квадратная матрица $A \in \mathbb{R}^{n \times n}$.
LU-разложение состоит в представлении матрицы $A$ в виде произведения двух треугольных матриц:

$$
A = L U
$$

где

- $L$ — нижняя треугольная матрица с единицами на диагонали
- $U$ — верхняя треугольная матрица

LU-разложение позволяет эффективно решать системы линейных уравнений $A x = b$ без вычисления обратной матрицы.




## Алгоритм построения LU-разложения

Пусть $A$ — матрица размера $n \times n$.
Инициализируем:

$$
L = I_n, \quad U = A
$$

где $I_n$ — единичная матрица.

### Шаги метода

Для каждого ведущего элемента $U[i,i]$, $i = 0,1,\dots,n-1$:

1. Проверяем, что элемент не слишком мал:

$$
|U[i,i]| < \varepsilon
$$

Если элемент слишком мал, ищем строку с максимальным по модулю элементом в столбце и меняем строки (частичный выбор ведущего).

2. Для каждой строки $j > i$ вычисляем множитель:

$$
L[j,i] = \frac{U[j,i]}{U[i,i]}.
$$

3. Вычитаем из строки $j$ строку $i$, умноженную на множитель:

$$
U[j,i:] = U[j,i:] - L[j,i] \cdot U[i,i:].
$$

После выполнения всех шагов получаем:

$$
A = L U
$$

## Решение системы $A x = b$ с помощью LU-разложения

1. Решаем прямую систему:

$$
L y = b
$$

методом прямого хода.

2. Решаем обратную систему:

$$
U x = y
$$

методом обратного хода.

В результате получаем решение исходной системы $x$.



In [99]:
import sympy
import numpy as np

In [100]:
A = np.array([[2, 4, -1, 5, 2],
          [-4, -5, 3, -8, 1],
          [2, -5, -4, 1, 8],
          [-6, 0, 7, -3, 1]],dtype=np.float64)

In [101]:
count_el_diag = min(A.shape)

In [102]:
L = np.zeros(A.shape, dtype=np.float64)
U = A.copy()

In [103]:
H = A.shape[0]
W = A.shape[1]
eps = 1e-12


for i in range(count_el_diag):
    L[i, i] = 1.0

    if abs(U[i, i]) < eps: # это текущий элемент ноль или очень маленькое число, то меняю строки. Если будет очень маленькое число, то все сломается
        max_row = np.argmax(np.abs(U[i:, i])) + i # ищу максимум по модулю в срезе
        if abs(U[max_row, i]) < eps:
            continue
        if max_row != i:
            U[[i, max_row], :] = U[[max_row, i], :]
            if i > 0:
                L[[i, max_row], :i] = L[[max_row, i], :i]

    for j in range(i+1, H): #пробегаюсь по j строкам. Начиная со 2й строки, так как первая остается без изменений
        mult = U[j, i] / U[i, i] # общий множитель между строками для зануления 1го ненулевого элемента в строке
        L[j, i] = mult # записываю в нижнюю матрицу
        U[j, i:] = U[j, i:] - mult * U[i, i:] # произвожу само действие для зануления

        U[j, i] = 0.0 # на всякий случай еще раз зануляю, чтобы не было точно значений меньше эпсилон
        U[j][np.abs(U[j]) < eps] = 0.0 # на всякий случай всю строку зануляю, чтобы не было точно значений меньше эпсилон


print(L)
print(U)

[[ 1.  0.  0.  0.  0.]
 [-2.  1.  0.  0.  0.]
 [ 1. -3.  1.  0.  0.]
 [-3.  4.  0.  1.  0.]]
[[  2.   4.  -1.   5.   2.]
 [  0.   3.   1.   2.   5.]
 [  0.   0.   0.   2.  21.]
 [  0.   0.   0.   4. -13.]]
